{
  "openapi": "3.0.0",
  "info": {
    "title": "Book-review-app-API",
    "version": "1.0.0",
    "description": "The Book Review App allows users to view a collection of books and submit ratings for individual titles. It provides endpoints for retrieving book information, managing user ratings, and ensuring that each user can only rate a book once. This API is designed to handle user interactions in a straightforward and efficient manner, making it easy to integrate into the application."
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "noauthAuth": {
        "type": "http",
        "scheme": "noauth"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "Books"
    },
    {
      "name": "Users"
    },
    {
      "name": "Ratings"
    }
  ],
  "paths": {
    "/books/": {
      "post": {
        "tags": [
          "Books"
        ],
        "summary": "Add Book",
        "description": "Add a new book to the collection with details like title, author, category, and description.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "bookTitle": "Stars",
                  "autherName": "Sample Author",
                  "category": "Scientific",
                  "bookDiscription": "This is a description of the book.",
                  "imageURL": "http://example.com/image.jpg",
                  "bookPDFURL": "http://example.com/sample.pdf"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Books"
        ],
        "summary": "Get all books",
        "description": "Retrieve all books in the collection, with their details.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/books/id": {
      "get": {
        "tags": [
          "Books"
        ],
        "summary": "Get Book by ID",
        "description": "Fetch details of a specific book by its ID.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Books"
        ],
        "summary": "Update Book",
        "description": "Update the information of a book by its ID.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "bookTitle": "Sample Book Title",
                  "autherName": "Sample Author",
                  "category": "Scientific",
                  "bookDiscription": "This is a description of the book.",
                  "imageURL": "http://example.com/image.jpg",
                  "bookPDFURL": "http://example.com/sample.pdf"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Books"
        ],
        "summary": "Delete Book by ID",
        "description": "Remove a book from the collection by its ID.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/users/": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Register user",
        "description": "Register a new user with information such as name, email, username, and password.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Sasmi",
                  "email": "sasmi@gmail.com",
                  "username": "sasmi",
                  "password": "Polsambal12",
                  "roleId": 2
                }
              }
            }
          }
        },
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get all Users",
        "description": "Get a list of all registered users.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/users/sign-in": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Login user",
        "description": "Authenticate and log in a user with their username and password.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "username": "sasmi",
                  "password": "Polsambal12"
                }
              }
            }
          }
        },
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/users/id": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get user by ID",
        "description": "Retrieve the details of a specific user by their ID.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update User",
        "description": "Update a user's information by their ID.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Anuka",
                  "email": "akuna123@gmail.com",
                  "username": "anuka",
                  "password": "Polsambal123",
                  "roleId": 2
                }
              }
            }
          }
        },
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete User by ID",
        "description": "Delete a user by their ID.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/ratings/": {
      "post": {
        "tags": [
          "Ratings"
        ],
        "summary": "Add user ratings",
        "description": "Add a rating and review for a specific book by a user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "ratings": 4,
                  "reviews": "very good",
                  "bookId": 5,
                  "userId": 3
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/ratings/bookid": {
      "get": {
        "tags": [
          "Ratings"
        ],
        "summary": "Get Ratings by Book Id",
        "description": "Retrieve all ratings and reviews for a specific book by its ID.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/ratings/avgrating/bookid": {
      "get": {
        "tags": [
          "Ratings"
        ],
        "summary": "Average rating",
        "description": "Get the average rating of a specific book by its ID.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/ratings/bookid/userid": {
      "get": {
        "tags": [
          "Ratings"
        ],
        "summary": "Get Rating by BookId,UserId",
        "description": "Retrieve the rating given by a specific user for a specific book.",
        "security": [
          {
            "noauthAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Ratings"
        ],
        "summary": "Update Ratings",
        "description": "Update the rating and review given by a user for a specific book.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "ratings": 5,
                  "reviews": "very good",
                  "bookId": 1,
                  "userId": 1
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Ratings"
        ],
        "summary": "Delete Ratings",
        "description": "Remove the rating and review given by a user for a specific book.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}